# Linear Algebra for CpE¶


# Laboratory 6 : Matrices

Now that you have a fundamental knowledge about vector representations, we'll try to look into greater dimensions.

# Objectives
At the end of this activity you will be able to:

1. Be familiar with matrices and their relation to linear equations.

2. Perform basic matrix operations.

3. Program and translate matrix equations and operations using Python.

# Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

# Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$ A = \left\{ \begin{array}\\ x + y \\ 4x - 10y \end{array} \right. \\ B = \left\{ \begin{array}\\ x+y+z \\ 3x -2y -z \\ -x + 4y +2z \end{array} \right. $$
We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$ A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\ B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix} $$
So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

# Declaring Matrices
Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&amp;a_{(0,1)}&amp;\dots&amp;a_{(0,j-1)}\\
a_{(1,0)}&amp;a_{(1,1)}&amp;\dots&amp;a_{(1,j-1)}\\
\vdots&amp;\vdots&amp;\ddots&amp;\vdots&amp;\\
a_{(i-1,0)}&amp;a_{(i-1,1)}&amp;\dots&amp;a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using shape, dimensions and size attributes, we'll use them to analyze these matrices.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

In [ ]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(H)

# Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their shape and another is according to their element values. We'll try to go through them.

# According to shape

# Row and Column Matrices
Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

# Square Matrices
Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

# According to element values

# Null Matrix
A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

# Zero Matrix
A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [6]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Ones Matrix
A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

# Diagonal Matrix
A diagonal matrix is a square matrix that has values only at the diagonal of the matrix.

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

In [ ]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

# Identity Matrix
An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Upper Triangular Matrix
An upper triangular matrix is a matrix that has no values below the diagonal.

In [ ]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

# Lower Triangular Matrix
A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

# Practice

Given the linear combination below, try to create a corresponding matrix representing it.
$$\theta = 5x + 3y - z$$

In [ ]:
theta = np.array([
              [5,3,-1],
])
describe_mat(theta)

1. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.
$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$

In [ ]:
number2_mat = np.array([
             [1,2,1],
             [0,4,-1],
             [0,0,10]
])
describe_mat(number2_mat)

2. Given the matrix below, express it as a linear combination in a markdown.

In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

$$G=\left\{\begin{array} 1g_1+7g_2+8g_3 \\2g_1+2g_2+2g_3\\4g_1+6g_2+7g_3 \end{array}\right.$$

3.Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

$$ H = \left\{\begin{array} 1x_1\\ 2x_1+ 2y_2\\ 4x_1+ 6y_2 +7z_3 \end{array}\right. $$


# Matrix Algebra

# Addition

In [ ]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

In [ ]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

# Subtraction

In [ ]:
A-B

In [ ]:
3-B == 3*np.ones(B.shape)-B

# Element-wise Multiplication

In [ ]:
A*B
np.multiply(A,B)

In [ ]:
2*A

In [ ]:
alpha=10**-10
A/(alpha+B)

In [ ]:
np.add(A,B)

# Activity

# Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.

2. Displays whether the matrix is square or non-square.

3. Displays whether the matrix is an empty matrix.

4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [4]:
def mat_desc(matrix):
    
    print(f'{matrix}\n\n'
      
          
            # prints the shape, size, and rank of the matrix
          
        f'The shape of the matrix is: {matrix.shape}\n'
        f'The size of the matrix is: {np.product(matrix.shape)}\n'
        f'The rank of the matrix is: {matrix.ndim}')
    
    # matrix.size determines the total number of elements in an array 
    if matrix.size > 0:
       
        is_ones = True if np.all((matrix == 1)) else False  #checks if all the elements in the array is 1
       
        is_zero = True if np.all((matrix == 0)) else False  #checks if all the elements in the array is 0
       
        is_square = True if matrix.shape[0] == matrix.shape[1] else False  #checks if row is equal to column size
        
        
        
        # checks if the matrix is a square matrix and an identity matrix 
        
        
        is_identity = True if matrix.shape[0] == matrix.shape[1] and np.allclose(matrix, np.eye(matrix.shape[0])) else False
        
        
        
        
        # prints if the matrix is a square, identity, ones,or zero
        
        
        print(f'Is the matrix a ones matrix?: {is_ones}\n'
        f'Is the matrix a zero matrix?: {is_zero}\n'
        f'Is the matrix a square?: {is_square}\n'
        f'Is the matrix an identity matrix?: {is_identity}\n\n'
        )
    else:
        print("The Matrix is Null")

In [5]:
mat_1 = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]
])
mat_2 = np.array([
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]
])
mat_3 = np.array([
    [15, 6, 9],
    [7, 15, 8],
    [11, 12, 15]
])
mat_4 = np.array([
    [20, 21, 31, 41],
    [50, 51, 61, 71],
    [80, 81, 91, 100]
])
mat_5 = np.array([
    [1000000,4444,999999],
    [2000000,555,66],
    [3000000,8888,77],
])

print(" First Matrix :")
mat_desc(mat_1)
print(" Second Matrix :")
mat_desc(mat_2)
print("Third Matrix :")
mat_desc(mat_3)
print("Fourth Matrix :")
mat_desc(mat_4)
print("Fifth Matrix :")
mat_desc(mat_5)

 First Matrix :
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

The shape of the matrix is: (6, 6)
The size of the matrix is: 36
The rank of the matrix is: 2
Is the matrix a ones matrix?: False
Is the matrix a zero matrix?: True
Is the matrix a square?: True
Is the matrix an identity matrix?: False


 Second Matrix :
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

The shape of the matrix is: (5, 5)
The size of the matrix is: 25
The rank of the matrix is: 2
Is the matrix a ones matrix?: True
Is the matrix a zero matrix?: False
Is the matrix a square?: True
Is the matrix an identity matrix?: False


Third Matrix :
[[15  6  9]
 [ 7 15  8]
 [11 12 15]]

The shape of the matrix is: (3, 3)
The size of the matrix is: 9
The rank of the matrix is: 2
Is the matrix a ones matrix?: False
Is the matrix a zero matrix?: False
Is the matrix a square?: True
Is the matrix an identity matrix?: False


Fourth Matrix :
[[ 20  21  31  41]
 [ 50 

# Task 2
Create a function named mat_operations() that takes in two matrices or scalars a input parameters it should:

1. Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.

2. Determines if the matrices are viable for operation and returns your own error message if they are not viable.

3. Returns the sum of the matrices.

4. Returns the difference of the matrices.

5. Returns the element-wise multiplication of the matrices.

6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [6]:
def mat_operations(mat1,mat2):
    alpha = 10**-10
    
    if np.isscalar(mat1):
        print("The first parameter is a scalar")
    else:
        print(f'1st matrix:\n {mat1}\n\n'
        f'The shape of the 1st matrix is: {mat1.shape}\n'
        f'The size of the 1st matrix is: {np.product(mat1.shape)}\n'
        f'The rank of the 1st matrix is: {mat1.ndim}')
        if mat1.size > 0:
            
            
            
            is_ones = True if np.all((mat1 == 1)) else False #checks if all the elements in the array is 1
          
            is_zero = True if np.all((mat1 == 0)) else False   #checks if all the elements in the array is 0
           
            is_square = True if mat1.shape[0] == mat1.shape[1] else False  # checks if row is equal to column size
            
            
            
            
            # checks if the matrix is a square matrix and an identity matrix using np.allclose
            is_identity = True if mat1.shape[0] == mat1.shape[1] and np.allclose(mat1, np.eye(mat1.shape[0])) else False
            
            
            
            # prints if the matrix is a square, identity, ones, and/or zero
            
            print(f'Is the matrix a ones matrix?: {is_ones}\n'
            f'Is the matrix a zero matrix?: {is_zero}\n'
            f'Is the matrix a square?: {is_square}\n'
            f'Is the matrix an identity matrix?: {is_identity}\n\n'
            )
        else:
            print("The Matrix is Null or Empty")
            
    if np.isscalar(mat2):
        print("The second parameter is a scalar\n")
    else:
        print(f'2nd matrix:\n {mat2}\n\n'
        f'The shape of the 2nd matrix is: {mat2.shape}\n'
        f'The size of the 2nd matrix is: {np.product(mat2.shape)}\n'
        f'The rank of the 2nd matrix is: {mat2.ndim}')
        if mat2.size > 0:
            
            
            
            is_ones = True if np.all((mat2 == 1)) else False #checks if all the elements in the array is 1
          
            is_zero = True if np.all((mat2 == 0)) else False   #checks if all the elements in the array is 0
          
            is_square = True if mat2.shape[0] == mat2.shape[1] else False   # checks if row is equal to column size
            
            
            # checks if the matrix is a square matrix and an identity matrix using np.allclose
        
            is_identity = True if mat2.shape[0] == mat2.shape[1] and np.allclose(mat2, np.eye(mat2.shape[0])) else False
            
            
            # prints if the matrix is a square, identity, ones, and/or zero
            
            print(f'Is the matrix a ones matrix?: {is_ones}\n'
            f'Is the matrix a zero matrix?: {is_zero}\n'
            f'Is the matrix a square?: {is_square}\n'
            f'Is the matrix an identity matrix?: {is_identity}\n\n')
        else:
            print("The Matrix is Null or Empty")
            
    if np.isscalar(mat1) == False and np.isscalar(mat2) == False:
        if (mat1.shape == mat2.shape):
            print(f'The sum of the matrices is: \n{np.sum(np.add(mat1,mat2))}\n'
                f'\nThe difference of the matrices is: \n{np.diff(np.subtract(mat1,mat2))}\n'
                f'\nThe element-wise multiplication of the matrices is: \n{np.multiply(mat1,mat2)}\n'
                f'\nThe element-wise division of the matrices is: \n{np.divide(mat1,mat2+alpha)}\n')
        else:
            print("The matrices aren't viable for operation\n")
    else:
        print("The parameters aren't viable for matrix operation\n")

In [17]:
mat_1 = np.array ([
    [1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1]
])
mat_2 = np.array([
    [33, 44, 55,77],
    [333, 444, 555,777],
    [66, 22, 11,99],
    [666, 222, 111,999],
    [88, 100, 22,10]
])

mat_3 = np.array([
    [51, 11, 21, 1, 2, 3],
    [101, 51, 41, 4, 5, 6],
    [31, 71, 81, 7, 8, 9]
])

mat_4 =  np.array([
    [31, 11, 21, 7, 8, 9],
    [11, 61, 41, 4, 5, 6],
    [31, 21, 81, 1, 2, 3]
])
mat_5 = np.array([
    [20, 30, 40, 50],
    [60, 70, 80, 90],
    [10, 100, 110, 120]
])

print("First Pair of Matrices:\n")
mat_operations(mat_1,mat_2)
print("\nSecond Pair of Matrices:\n")
mat_operations(mat_3,mat_4)
print("\nThird Pair of Matrices:\n")
mat_operations(mat_1,mat_5)

First Pair of Matrices:

1st matrix:
 [[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

The shape of the 1st matrix is: (6, 6)
The size of the 1st matrix is: 36
The rank of the 1st matrix is: 2
Is the matrix a ones matrix?: False
Is the matrix a zero matrix?: False
Is the matrix a square?: True
Is the matrix an identity matrix?: True


2nd matrix:
 [[ 33  44  55  77]
 [333 444 555 777]
 [ 66  22  11  99]
 [666 222 111 999]
 [ 88 100  22  10]]

The shape of the 2nd matrix is: (5, 4)
The size of the 2nd matrix is: 20
The rank of the 2nd matrix is: 2
Is the matrix a ones matrix?: False
Is the matrix a zero matrix?: False
Is the matrix a square?: False
Is the matrix an identity matrix?: False


The matrices aren't viable for operation


Second Pair of Matrices:

1st matrix:
 [[ 51  11  21   1   2   3]
 [101  51  41   4   5   6]
 [ 31  71  81   7   8   9]]

The shape of the 1st matrix is: (3, 6)
The size of the 1st matrix is: 18
The rank of the 1st 

# Conclusion
For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in agriculture?".